import { readFile, writeFile } from 'node:fs/promises';

const shell = await readFile(new URL('./control.html', import.meta.url), 'utf8');
const app = await readFile(new URL('./control-app.mjs', import.meta.url), 'utf8');
if (!shell.includes('/* APP_SCRIPT */') || /<\/script/i.test(app)) {
  throw Error('Invalid control page source');
}
const html = shell.replace('/* APP_SCRIPT */', () => app);
await writeFile(new URL('../lib/epaper/control-page.mjs', import.meta.url),
  '// Generated by node ui/build-ui.mjs; edit ui/control.html and ui/control-app.mjs.\n' +
  'export default ' + JSON.stringify(html) + ';\n');
console.log('Built lib/epaper/control-page.mjs');
